Disable sharing if email is not validated yet
ogorlab/ogor-frontend pull request #527
Opened 2021-01-21 16:48 UTC by andreighh

Refs: #515

2021-01-22 07:49 UTC, alexkiro requested changes
Nice work! I've had a few nit-picks here in there, but everything seems to be working ok.

2021-01-22 07:49 UTC, alexkiro commented on src/components/Modals/ShareModal.vue
> +          :disabled="userIsConfirmed === false"
`=== false` looks a bit awkward, I suggest we just put `!userIsConfirmed` instead :)

2021-01-22 07:49 UTC, alexkiro commented on src/components/Modals/ShareModal.vue
> +      <div v-if="unconfirmedUserError" class="unconfirmed">
I would use `!userIsConfirmed` for the condition here, instead of checking if the error message is truthy. As it's a bit more explicit, and we can get rid of `if` condition in the computed property later.

2021-01-22 07:49 UTC, alexkiro commented on src/components/Modals/ShareModal.vue
> +      if (!this.userIsConfirmed) {
No need for this conditional here.

2021-01-22 07:49 UTC, alexkiro commented on src/components/Modals/ShareModal.vue
> +            <br />
Using breakpoints here is a also a bit awkward, since it's more annoying to control the spacing. (which is too large ATM). I would add some margins here of about `1.5rem`

2021-01-22 07:49 UTC, alexkiro commented on src/components/Modals/ShareModal.vue
> +    padding-right: 2.5rem;
`2.5rem` looks too large to me. In the mocks it's only 2 AFAICT.

2021-01-22 07:49 UTC, alexkiro commented on src/components/Modals/ShareModal.vue
> +    color: @text-error;
The mocks use the brand orange color here.

2021-01-22 07:49 UTC, alexkiro commented on src/components/Modals/ShareModal.vue
> +      color: gray;
I'm pretty sure the color from the mocks is `@text-muted` here, as it's definitely is not the bland stock gray color :). I'm unable to confirm this from the mocks, I think the component is grouped. You can ask Vali if you want to be sure.

2021-01-22 07:49 UTC, alexkiro commented on src/components/Modals/ShareModal.vue
> +      max-width: 25.5rem;
I don't think this `max-width` is required at all :thinking: Can you explain why you've added, I might be missing something.

2021-01-22 07:49 UTC, alexkiro commented on src/components/Modals/ShareModal.vue
> +      color: black;
While `black` is correct here, please use the `@text-emphasis` variable.

2021-01-22 07:49 UTC, alexkiro commented on src/components/Modals/ShareModal.vue
> +.unconfirmed {
The mock has this with a rounded border of `@rounded-border-radius`, please add that as well.

2021-01-22 08:11 UTC, andreighh commented on src/components/Modals/ShareModal.vue
> +      max-width: 25.5rem;
Without this, the resend "link" can be clicked outside the text, was a little hack.

2021-01-22 08:30 UTC, alexkiro commented on src/components/Modals/ShareModal.vue
> +      max-width: 25.5rem;
A got it! The problem with this is that the width of the text will depend on what language the user has. You should be able to achieve something similar with either:

```
width: max-content;
```

or

```
width: min-content;
white-space: nowrap;
```

Don't remember which one works TBH :laughing:

2021-01-25 06:59 UTC, alexkiro requested changes

2021-01-25 06:59 UTC, alexkiro commented on src/components/Modals/ShareModal.vue
> +    color: orange;
Please use the same color as in the mocks, and not the stock "orange" color.

2021-01-25 07:57 UTC, andreighh commented on src/components/Modals/ShareModal.vue
> +    color: orange;
Sorry, I misunderstood what "brand" orange means. Now I get it.

2021-01-25 08:37 UTC, alexkiro approved these changes
Looks good now!

2021-01-25 08:37 UTC, merged