Redesign weather forecast widget
ogorlab/ogor-frontend pull request #620
Opened 2021-03-11 14:47 UTC by andreighh

Refs #586

2021-03-12 06:46 UTC, alexkiro requested changes
Really nice work! I left some minor comments.

---

I also noticed this scenario:

![Screenshot from 2021-03-12 08-37-52](https://user-images.githubusercontent.com/1538458/110902342-6ad42180-830e-11eb-8ebf-ec793358512a.png)

I suggest to make this text centered:

![Screenshot from 2021-03-12 08-40-35](https://user-images.githubusercontent.com/1538458/110902494-a5d65500-830e-11eb-9a14-d6d0139632a6.png)

And also align the icons in these scenarios. You should be able to do that if you put these 3 items into a separate a div 

![Screenshot from 2021-03-12 08-44-25](https://user-images.githubusercontent.com/1538458/110902882-3a40b780-830f-11eb-9e5e-91340deab918.png)

And making the container a flex box with column direction and ```justify-content: space-between```

2021-03-12 06:46 UTC, alexkiro commented on src/components/MapPanel/WeatherForecast.vue
> +    },
This doesn't need to be a method. You can instead make `selectedForecast` a computed property that returns `this.forecastOfToday[this.indexForecastOfToday];` and it will update automatically.

2021-03-12 06:46 UTC, alexkiro commented on src/components/MapPanel/WeatherForecast.vue
> +          </div>
This should be translated. Please add ```v-translate=""```

2021-03-12 06:46 UTC, alexkiro commented on src/components/MapPanel/WeatherForecast.vue
> +        >
Since this is an external link please add: 

```target="_blank" rel="noopener noreferrer"```

We want to open external links in new tabs so the user doesn't leave our application and we don't send referral information. 

---

The formatting is a bit weird here as well :thinking: It will probably look much nicer if:

```
<a href="https://openweathermap.org/" class="small muted data-source">
    openweathermap.org
</a>
```

2021-03-12 08:57 UTC, andreighh commented on src/components/MapPanel/WeatherForecast.vue
> +    },
I'm not sure I want `selectedForecast` to update automatically. It should only update with `this.forecastOfToday[this.indexForecastOfToday];` when the tab selected is the one for today, otherwise it should update with the forecast sent from `dailyForecast` in the `v-for`.

Definitely looking for suggestions on how to improve this.

2021-03-12 08:58 UTC, andreighh commented
The container trick sadly didn't work, looking for alternatives.
![image](https://user-images.githubusercontent.com/61791875/110916846-e8edf380-8321-11eb-9cc7-e16ff4edf4ad.png)

2021-03-12 09:18 UTC, andreighh commented
https://github.com/ogorlab/ogor-frontend/pull/620/commits/cf6d4e98037c3286c605a0f099ef759a368449f7 added some bugs, fixing first

2021-03-12 11:31 UTC, alexkiro commented
> The container trick sadly didn't work, looking for alternatives.
> ![image](https://user-images.githubusercontent.com/61791875/110916846-e8edf380-8321-11eb-9cc7-e16ff4edf4ad.png)

It seem you used `justify-content: space-evenly;` instead of `justify-content: space-between;` :smile:

2021-03-12 11:32 UTC, alexkiro commented
> It seem you used `justify-content: space-evenly;` instead of `justify-content: space-between;`

Also this needs to be put on the parent container, not the child.

2021-03-12 11:35 UTC, alexkiro commented on src/components/MapPanel/WeatherForecast.vue
> +    },
> I'm not sure I want `selectedForecast` to update automatically.

I'm pretty sure you do, as the only place you change indexForecastOfToday is in `incrementIndexForecastToday` and `decrementIndexForecastToday` and you call this function immediately after.

2021-03-12 11:38 UTC, alexkiro commented on src/components/MapPanel/WeatherForecast.vue
> +    },
Ooo, nevermind, the selected forecast can be one that is NOT today. Got it, you can disregard my comment then :)

2021-03-12 11:59 UTC, andreighh commented
> It seem you used `justify-content: space-evenly;` instead of `justify-content: space-between;`
I actually tried both and it seems like I pushed the wrong version, but I get it now. We don't want the icon and temps to be separated, but instead the group of them to be separated from the upper text (tested and it works!) :D

2021-03-12 12:18 UTC, andreighh commented on src/components/MapPanel/WeatherForecast.vue
> +    },
Yep, I did that, because I did not want to use different data in the template, it was much easier to use `selectedForecast` for everything.

2021-03-15 06:03 UTC, alexkiro approved these changes
Nice work

2021-03-15 06:03 UTC, merged